name:                iucc
version:             0.1.0
synopsis:            Haskell implementation of the IU Compiler Course
github:              dogonthehorizon/iucc
license:             MIT
author:              Fernando Freire
maintainer:          Fernando Freire <dogonthehorizon@gmail.com>
copyright:           2023 Fernando Freire
category:            Compiler
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - megaparsec
  - text
  - transformers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
  - BangPatterns
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingVia
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - OverloadedStrings
  - PatternSynonyms
  - ScopedTypeVariables
  - ImportQualifiedPost

library:
  source-dirs: src

executables:
  iucc:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - iucc
      - optparse-generic

tests:
  iucc-test:
    build-tools: tasty-discover:tasty-discover ^>=4.2.1
    main: Tasty.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - iucc
      - hedgehog
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-hedgehog
